### ISSUE TITLE
Show your pride with badges

### ISSUE THREAD

**Issue by ravage84** [syntaxera/cakephp-sparkpost-plugin#15] opened 2016-04-26 10:59 UTC
When you integrate witht he varoius cloud (software quality) services, you should show your pride with badges in the README.

**Comment by robojamison** [comment] 2016-04-26 12:27
Duplicate to #4

**Comment by robojamison** [comment] 2016-04-26 19:43
Closing as duplicate of #4.

**Closed by robojamison** 2016-04-26 19:43 UTC
